# Generated by Django 4.1 on 2023-02-24 02:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone_number', models.CharField(max_length=13)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('Currency', models.CharField(max_length=5)),
                ('operator', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MobileTransactions',
            fields=[
                ('id', models.DecimalField(decimal_places=2, max_digits=100)),
                ('amount', models.IntegerField()),
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ref', models.UUIDField(verbose_name=uuid.UUID('61b639da-5b9f-4365-a130-9c6aac073d0f'))),
                ('status', models.CharField(max_length=15)),
                ('transaction_charges', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_data', to='codelab_api.countrydata')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_country', to='codelab_api.countrydata')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_1', to='codelab_api.countrydata')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_phonenumber', to='codelab_api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_merchant_transfer', models.BooleanField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_data', to='codelab_api.mobiletransactions')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_disbursement', to='codelab_api.countrydata')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_disburse', to='codelab_api.countrydata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_disbursement', to='codelab_api.mobiletransactions')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransactions',
            fields=[
                ('beneficiary_name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('fee', models.IntegerField()),
                ('bank_name', models.CharField(max_length=255)),
                ('narration', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=255)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_details', to='codelab_api.client')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='codelab_api.client')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_bank', to='codelab_api.countrydata')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transfer_id', serialize=False, to='codelab_api.banktransactions')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_details_2', to='codelab_api.client')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_number_2', to='codelab_api.banktransactions')),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_code_4', to='codelab_api.banktransactions')),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_name1', to='codelab_api.banktransactions')),
                ('beneficiary_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_name_2', to='codelab_api.banktransactions')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codelab_api.client')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_bank_3', to='codelab_api.countrydata')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_3', to='codelab_api.banktransactions')),
                ('narration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration_2', to='codelab_api.banktransactions')),
            ],
        ),
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('code', models.CharField(max_length=100)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_bank', serialize=False, to='codelab_api.client')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banklist_fullname_2', to='codelab_api.client')),
            ],
        ),
    ]
