# Generated by Django 4.1 on 2023-02-24 03:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiletransactions',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='mobiletransactions',
            name='id',
            field=models.DecimalField(decimal_places=2, max_digits=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mobiletransactions',
            name='ref',
            field=models.UUIDField(verbose_name=uuid.UUID('cb21b771-da5c-4d25-92ad-bb41551a1dce')),
        ),
    ]
