# Generated by Django 4.1 on 2023-02-24 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_api', '0002_remove_mobiletransactions_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrydata',
            old_name='Currency',
            new_name='currency',
        ),
        migrations.AlterField(
            model_name='mobiletransactions',
            name='ref',
            field=models.UUIDField(verbose_name=uuid.UUID('f9613cb6-05ad-4862-8de3-1dcbe4d42cc5')),
        ),
    ]
