# Generated by Django 3.2.8 on 2022-08-15 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('current_users', models.ManyToManyField(blank=True, related_name='current_rooms', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('end_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone_no', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('network_transaction_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('object', models.CharField(blank=True, max_length=50, null=True)),
                ('sms', models.CharField(blank=True, max_length=50, null=True)),
                ('module_id', models.CharField(blank=True, max_length=50, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=20, null=True)),
                ('isDisbursment', models.BooleanField(default=True)),
                ('networkProcesseAt', models.DateTimeField(max_length=50, null=True)),
                ('processeAt', models.DateTimeField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pal.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
